server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: person-web-service
  datasource:
    url: jdbc:mysql://localhost:3306/person_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Steam API相关配置
steam:
  api-key: FE6CF79D6AB8A5C5F057A76F9E92C9BC
  user-id: 76561198211620885

# 日志配置
logging:
  level:
    root: INFO
    com.person.web: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/person-web-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30 